fix: Arreglar la manera en la que guarda, monta y ejecuta los ficheros de php

diff --git a/charts/templates/php-deployment.yaml b/charts/templates/php-deployment.yaml
--- a/charts/templates/php-deployment.yaml
+++ b/charts/templates/php-deployment.yaml
@@ -20,11 +20,10 @@ spec:
         command: ["/bin/sh", "-c"]
         args:
         - |
+          echo "Copying data to persistent volume..." && \
           cp -R /var/www/* /mnt/www && \
           chown -R www-data:www-data /mnt/www && \
           chmod -R 775 /mnt/www
-          composer install --working-dir=/mnt/www
-          node -v && npm -v npm install && npm run build
         volumeMounts:
         - name: php-code
           mountPath: /mnt/www
@@ -39,6 +38,14 @@ spec:
         command: ["/bin/sh", "-c"]
         args:
         - |
+          if [ ! -f /var/www/composer.json ]; then
+            echo "composer.json not found in /var/www. Exiting.";
+            exit 1;
+          fi;
+          chown -R www-data:www-data /var/www && \
+          chmod -R 775 /var/www && \
+          composer install --working-dir=/var/www && \
+          npm install && npm run build && \
           php-fpm
       volumes:
       - name: php-code
